CREATE DATABASE IF NOT EXISTS COMMERCE_GUARDIAN_AGENT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE COMMERCE_GUARDIAN_AGENT;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS AGENT_ITEM;
DROP TABLE IF EXISTS AGENT_CONTEXT_SNAPSHOT;
DROP TABLE IF EXISTS AGENT_WORKFLOW_QUESTION;
DROP TABLE IF EXISTS AGENT_WORKFLOW_RUN;
DROP TABLE IF EXISTS EXTERNAL_ACTION_COMMAND;
DROP TABLE IF EXISTS EXTERNAL_ACTION_RESULT;
DROP TABLE IF EXISTS AGENT_TURN;
DROP TABLE IF EXISTS AGENT_THREAD;
DROP TABLE IF EXISTS DEMO_LOGISTICS_EVENT;
DROP TABLE IF EXISTS DEMO_ORDER;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE DEMO_ORDER (
    ORDER_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(64) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    DAYS_SINCE_DELIVERY INT DEFAULT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    EXPECTED_DELIVERY_AT DATETIME(6) DEFAULT NULL,
    LAST_LOGISTICS_AT DATETIME(6) DEFAULT NULL,
    LOGISTICS_STATUS VARCHAR(32) DEFAULT NULL,
    PAID_AMOUNT DECIMAL(19,2) DEFAULT NULL,
    CURRENCY VARCHAR(8) DEFAULT NULL,
    ITEM_SUMMARY VARCHAR(256) DEFAULT NULL,
    HIDDEN_AT DATETIME(6) DEFAULT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_DEMO_ORDER PRIMARY KEY (ORDER_ID),
    INDEX IDX_DEMO_ORDER_USER_STATUS (USER_ID, STATUS),
    INDEX IDX_DEMO_ORDER_USER_VISIBILITY_TIME (USER_ID, HIDDEN_AT, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE DEMO_LOGISTICS_EVENT (
    EVENT_ID VARCHAR(64) NOT NULL,
    ORDER_ID VARCHAR(64) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    LOCATION VARCHAR(256) DEFAULT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    OCCURRED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_DEMO_LOGISTICS_EVENT PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_DEMO_LOGISTICS_EVENT_ORDER FOREIGN KEY (ORDER_ID) REFERENCES DEMO_ORDER (ORDER_ID),
    INDEX IDX_DEMO_LOGISTICS_EVENT_ORDER_TIME (ORDER_ID, OCCURRED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE AGENT_THREAD (
    THREAD_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    TITLE VARCHAR(256) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    CONTEXT_TYPE VARCHAR(64) DEFAULT NULL,
    CONTEXT_ID VARCHAR(128) DEFAULT NULL,
    OPEN_QUESTION_ID VARCHAR(64) DEFAULT NULL,
    NEXT_SEQUENCE BIGINT NOT NULL DEFAULT 0,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_AGENT_THREAD PRIMARY KEY (THREAD_ID),
    INDEX IDX_AGENT_THREAD_OWNER_UPDATED (USER_ID, UPDATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE AGENT_TURN (
    TURN_ID VARCHAR(64) NOT NULL,
    THREAD_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    CLIENT_REQUEST_ID VARCHAR(128) NOT NULL,
    INPUT_TEXT VARCHAR(10000) NOT NULL COMMENT '普通 Turn 消息最多 256 字符；同时容纳结构化 Workflow 回答',
    STATUS VARCHAR(32) NOT NULL,
    QUEUE_POSITION INT DEFAULT NULL,
    WORKFLOW_RUN_ID VARCHAR(64) DEFAULT NULL,
    WORKFLOW_QUESTION_ID VARCHAR(64) DEFAULT NULL,
    WORKFLOW_CHECKPOINT_ID VARCHAR(128) DEFAULT NULL,
    WORKFLOW_QUESTION_VERSION BIGINT DEFAULT NULL,
    WORKFLOW_ANSWERS_JSON LONGTEXT DEFAULT NULL,
    ERROR_CODE VARCHAR(128) DEFAULT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    STARTED_AT DATETIME(6) DEFAULT NULL,
    FINISHED_AT DATETIME(6) DEFAULT NULL,
    VERSION_NO BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT PK_AGENT_TURN PRIMARY KEY (TURN_ID),
    CONSTRAINT UQ_AGENT_TURN_REQUEST UNIQUE (USER_ID, CLIENT_REQUEST_ID),
    CONSTRAINT FK_AGENT_TURN_THREAD FOREIGN KEY (THREAD_ID) REFERENCES AGENT_THREAD (THREAD_ID),
    INDEX IDX_AGENT_TURN_THREAD_STATUS (THREAD_ID, STATUS, CREATED_AT),
    INDEX IDX_AGENT_TURN_WORKFLOW (USER_ID, WORKFLOW_RUN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE AGENT_ITEM (
    ITEM_ID VARCHAR(64) NOT NULL,
    THREAD_ID VARCHAR(64) NOT NULL,
    TURN_ID VARCHAR(64) DEFAULT NULL,
    SEQUENCE_NO BIGINT NOT NULL,
    ITEM_TYPE VARCHAR(64) NOT NULL,
    PAYLOAD_JSON LONGTEXT NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_AGENT_ITEM PRIMARY KEY (ITEM_ID),
    CONSTRAINT UQ_AGENT_ITEM_SEQUENCE UNIQUE (THREAD_ID, SEQUENCE_NO),
    CONSTRAINT FK_AGENT_ITEM_THREAD FOREIGN KEY (THREAD_ID) REFERENCES AGENT_THREAD (THREAD_ID),
    INDEX IDX_AGENT_ITEM_THREAD_SEQUENCE (THREAD_ID, SEQUENCE_NO),
    INDEX IDX_AGENT_ITEM_TURN_SEQUENCE (TURN_ID, SEQUENCE_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE AGENT_CONTEXT_SNAPSHOT (
    SNAPSHOT_ID VARCHAR(64) NOT NULL,
    THREAD_ID VARCHAR(64) NOT NULL,
    THROUGH_SEQUENCE BIGINT NOT NULL,
    VERSION_NO BIGINT NOT NULL,
    ESTIMATED_TOKENS INT NOT NULL,
    SUMMARY LONGTEXT NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_AGENT_CONTEXT_SNAPSHOT PRIMARY KEY (SNAPSHOT_ID),
    CONSTRAINT FK_AGENT_CONTEXT_SNAPSHOT_THREAD FOREIGN KEY (THREAD_ID) REFERENCES AGENT_THREAD (THREAD_ID),
    INDEX IDX_AGENT_CONTEXT_SNAPSHOT_LATEST (THREAD_ID, THROUGH_SEQUENCE DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE AGENT_WORKFLOW_RUN (
    RUN_ID VARCHAR(64) NOT NULL,
    THREAD_ID VARCHAR(64) NOT NULL,
    TURN_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    WORKFLOW_TYPE VARCHAR(64) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    VERSION_NO BIGINT NOT NULL DEFAULT 0,
    STEPS_JSON LONGTEXT NOT NULL,
    STATE_JSON LONGTEXT NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_AGENT_WORKFLOW_RUN PRIMARY KEY (RUN_ID),
    CONSTRAINT UQ_AGENT_WORKFLOW_RUN_SOURCE UNIQUE (USER_ID, TURN_ID, WORKFLOW_TYPE),
    CONSTRAINT FK_AGENT_WORKFLOW_RUN_THREAD FOREIGN KEY (THREAD_ID) REFERENCES AGENT_THREAD (THREAD_ID),
    INDEX IDX_AGENT_WORKFLOW_RUN_OWNER (USER_ID, UPDATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE AGENT_WORKFLOW_QUESTION (
    QUESTION_ID VARCHAR(64) NOT NULL,
    RUN_ID VARCHAR(64) NOT NULL,
    THREAD_ID VARCHAR(64) NOT NULL,
    TURN_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    CHECKPOINT_ID VARCHAR(128) NOT NULL,
    STEP_NO INT NOT NULL DEFAULT 0,
    VERSION_NO BIGINT NOT NULL DEFAULT 0,
    ANSWER_TURN_ID VARCHAR(64) DEFAULT NULL,
    ANSWER_ENQUEUE_STATUS VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
    TITLE VARCHAR(256) NOT NULL,
    PROMPT VARCHAR(2000) NOT NULL,
    FIELDS_JSON LONGTEXT NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    ANSWERED_AT DATETIME(6) DEFAULT NULL,
    CONSTRAINT PK_AGENT_WORKFLOW_QUESTION PRIMARY KEY (QUESTION_ID),
    CONSTRAINT UQ_AGENT_WORKFLOW_QUESTION_RUN_STEP UNIQUE (RUN_ID, STEP_NO),
    CONSTRAINT UQ_AGENT_WORKFLOW_QUESTION_ANSWER_TURN UNIQUE (ANSWER_TURN_ID),
    CONSTRAINT FK_AGENT_WORKFLOW_QUESTION_RUN FOREIGN KEY (RUN_ID) REFERENCES AGENT_WORKFLOW_RUN (RUN_ID),
    CONSTRAINT FK_AGENT_WORKFLOW_QUESTION_THREAD FOREIGN KEY (THREAD_ID) REFERENCES AGENT_THREAD (THREAD_ID),
    INDEX IDX_AGENT_WORKFLOW_QUESTION_OPEN (USER_ID, THREAD_ID, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE EXTERNAL_ACTION_COMMAND (
    COMMAND_ID VARCHAR(64) NOT NULL,
    RUN_ID VARCHAR(64) NOT NULL,
    THREAD_ID VARCHAR(64) NOT NULL,
    TURN_ID VARCHAR(64) DEFAULT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    ACTION_TYPE VARCHAR(32) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(256) NOT NULL,
    PAYLOAD_JSON LONGTEXT NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    VERSION_NO BIGINT NOT NULL DEFAULT 0,
    ATTEMPT_COUNT INT NOT NULL DEFAULT 0,
    MAX_ATTEMPTS INT NOT NULL DEFAULT 3,
    RETRY_CYCLE_ATTEMPT_COUNT INT NOT NULL DEFAULT 0,
    NEXT_ATTEMPT_AT DATETIME(6) DEFAULT NULL,
    LEASE_OWNER VARCHAR(128) DEFAULT NULL,
    LEASE_UNTIL DATETIME(6) DEFAULT NULL,
    LAST_ERROR_CODE VARCHAR(128) DEFAULT NULL,
    LAST_ERROR_MESSAGE VARCHAR(1000) DEFAULT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    COMPLETED_AT DATETIME(6) DEFAULT NULL,
    CONSTRAINT PK_EXTERNAL_ACTION_COMMAND PRIMARY KEY (COMMAND_ID),
    CONSTRAINT UQ_EXTERNAL_ACTION_IDEMPOTENCY UNIQUE (USER_ID, IDEMPOTENCY_KEY),
    CONSTRAINT FK_EXTERNAL_ACTION_THREAD FOREIGN KEY (THREAD_ID) REFERENCES AGENT_THREAD (THREAD_ID),
    INDEX IDX_EXTERNAL_ACTION_DUE (STATUS, NEXT_ATTEMPT_AT, LEASE_UNTIL),
    INDEX IDX_EXTERNAL_ACTION_RUN (USER_ID, RUN_ID),
    INDEX IDX_EXTERNAL_ACTION_THREAD_STATUS (THREAD_ID, STATUS, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE EXTERNAL_ACTION_RESULT (
    RESULT_ID VARCHAR(64) NOT NULL,
    COMMAND_ID VARCHAR(64) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(256) NOT NULL,
    ACTION_TYPE VARCHAR(32) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    RESPONSE_JSON LONGTEXT NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_EXTERNAL_ACTION_RESULT PRIMARY KEY (RESULT_ID),
    CONSTRAINT UQ_EXTERNAL_ACTION_RESULT_COMMAND UNIQUE (COMMAND_ID),
    CONSTRAINT UQ_EXTERNAL_ACTION_RESULT_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT FK_EXTERNAL_ACTION_RESULT_COMMAND FOREIGN KEY (COMMAND_ID) REFERENCES EXTERNAL_ACTION_COMMAND (COMMAND_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO DEMO_ORDER (ORDER_ID, USER_ID, STATUS, DAYS_SINCE_DELIVERY, CREATED_AT, EXPECTED_DELIVERY_AT, LAST_LOGISTICS_AT, LOGISTICS_STATUS, PAID_AMOUNT, CURRENCY, ITEM_SUMMARY, HIDDEN_AT, UPDATED_AT) VALUES
('ORDER-PAID-001', 'demo-user-1', 'PAID', NULL, DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 72 HOUR), NULL, NULL, NULL, 99.00, 'CNY', '无线降噪耳机', NULL, CURRENT_TIMESTAMP(6)),
('ORDER-SHIPPED-STALLED-001', 'demo-user-1', 'SHIPPED', NULL, DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 120 HOUR), DATE_ADD(CURRENT_TIMESTAMP(6), INTERVAL 24 HOUR), DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 72 HOUR), 'IN_TRANSIT', 129.00, 'CNY', '家用咖啡机滤芯套装', NULL, CURRENT_TIMESTAMP(6)),
('ORDER-TODAY-PAID-001', 'demo-user-1', 'PAID', NULL, DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 3 HOUR), NULL, NULL, NULL, 39.90, 'CNY', '棉质家居拖鞋', NULL, CURRENT_TIMESTAMP(6)),
('ORDER-TODAY-DELIVERED-001', 'demo-user-1', 'DELIVERED', 0, DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 8 HOUR), DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 1 HOUR), DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 1 HOUR), 'DELIVERED', 199.00, 'CNY', '便携榨汁杯', NULL, CURRENT_TIMESTAMP(6)),
('ORDER-7D-DELIVERED-001', 'demo-user-1', 'DELIVERED', 2, DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 48 HOUR), DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 12 HOUR), DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 12 HOUR), 'DELIVERED', 599.00, 'CNY', '人体工学办公椅', NULL, CURRENT_TIMESTAMP(6)),
('ORDER-7D-CANCELLED-001', 'demo-user-1', 'CANCELLED', NULL, DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 120 HOUR), NULL, NULL, NULL, 59.00, 'CNY', '旅行收纳袋', NULL, CURRENT_TIMESTAMP(6)),
('ORDER-SHIPPED-OK-001', 'demo-user-1', 'SHIPPED', NULL, DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 144 HOUR), DATE_ADD(CURRENT_TIMESTAMP(6), INTERVAL 36 HOUR), DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 6 HOUR), 'IN_TRANSIT', 299.00, 'CNY', '智能台灯', NULL, CURRENT_TIMESTAMP(6)),
('ORDER-SHIPPED-STALLED-002', 'demo-user-1', 'SHIPPED', NULL, DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 168 HOUR), DATE_ADD(CURRENT_TIMESTAMP(6), INTERVAL 48 HOUR), DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 120 HOUR), 'IN_TRANSIT', 109.00, 'CNY', '户外保温水壶', NULL, CURRENT_TIMESTAMP(6)),
('ORDER-FOREIGN-001', 'demo-user-2', 'PAID', NULL, DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 72 HOUR), NULL, NULL, NULL, 88.00, 'CNY', '其他用户订单', NULL, CURRENT_TIMESTAMP(6));

INSERT INTO DEMO_LOGISTICS_EVENT (EVENT_ID, ORDER_ID, STATUS, LOCATION, DESCRIPTION, OCCURRED_AT) VALUES
('LOG-STALLED-001', 'ORDER-SHIPPED-STALLED-001', 'PICKED_UP', '深圳分拨中心', '包裹已由承运商揽收。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 96 HOUR)),
('LOG-STALLED-002', 'ORDER-SHIPPED-STALLED-001', 'IN_TRANSIT', '广州转运中心', '包裹正在转运。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 72 HOUR)),
('LOG-TODAY-DELIVERED-001', 'ORDER-TODAY-DELIVERED-001', 'DELIVERED', '上海配送站', '包裹已送达。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 1 HOUR)),
('LOG-SHIPPED-OK-001', 'ORDER-SHIPPED-OK-001', 'IN_TRANSIT', '杭州转运中心', '包裹已进入下一站。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 6 HOUR)),
('LOG-SHIPPED-STALLED-002-001', 'ORDER-SHIPPED-STALLED-002', 'PICKED_UP', '北京分拨中心', '包裹已由承运商揽收。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 144 HOUR)),
('LOG-SHIPPED-STALLED-002-002', 'ORDER-SHIPPED-STALLED-002', 'IN_TRANSIT', '天津转运中心', '包裹正在转运。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 120 HOUR));
