ALTER TABLE AGENT_CONTEXT_SNAPSHOT
    ADD COLUMN FORMAT_VERSION SMALLINT NOT NULL DEFAULT 1 AFTER CREATED_AT,
    ADD COLUMN BASE_SNAPSHOT_ID VARCHAR(64) NULL AFTER FORMAT_VERSION,
    ADD COLUMN SOURCE_FROM_SEQUENCE BIGINT NOT NULL DEFAULT 1 AFTER BASE_SNAPSHOT_ID,
    ADD COLUMN SOURCE_ESTIMATED_TOKENS INT NOT NULL DEFAULT 0 AFTER SOURCE_FROM_SEQUENCE,
    ADD COLUMN SUMMARY_PROMPT_VERSION VARCHAR(64) NOT NULL DEFAULT 'legacy' AFTER SOURCE_ESTIMATED_TOKENS,
    ADD COLUMN SUMMARY_MAX_OUTPUT_TOKENS INT NOT NULL DEFAULT 0 AFTER SUMMARY_PROMPT_VERSION;

CREATE INDEX IDX_AGENT_CONTEXT_SNAPSHOT_BASE
    ON AGENT_CONTEXT_SNAPSHOT (BASE_SNAPSHOT_ID);
