ALTER TABLE AGENT_WORKFLOW_RUN
    ADD COLUMN ORCHESTRATION_VERSION VARCHAR(32) NOT NULL DEFAULT 'LEGACY_V1'
        AFTER WORKFLOW_TYPE;

UPDATE AGENT_WORKFLOW_RUN
SET ORCHESTRATION_VERSION = 'LEGACY_V1'
WHERE ORCHESTRATION_VERSION IS NULL OR ORCHESTRATION_VERSION = '';
