ALTER TABLE AGENT_GRAPH_SNAPSHOT
    ADD COLUMN ORCHESTRATION_VERSION VARCHAR(32) NOT NULL DEFAULT 'LEGACY_V1'
        AFTER FACTS_FINGERPRINT;

UPDATE AGENT_GRAPH_SNAPSHOT
SET ORCHESTRATION_VERSION = 'LEGACY_V1'
WHERE ORCHESTRATION_VERSION IS NULL OR ORCHESTRATION_VERSION = '';
