ALTER TABLE EXTERNAL_ACTION_COMMAND
    ADD COLUMN OUTCOME_STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING' AFTER STATUS,
    ADD COLUMN VERIFICATION_ATTEMPT_COUNT INT NOT NULL DEFAULT 0 AFTER RETRY_CYCLE_ATTEMPT_COUNT,
    ADD COLUMN MAX_VERIFICATION_ATTEMPTS INT NOT NULL DEFAULT 3 AFTER VERIFICATION_ATTEMPT_COUNT;

UPDATE EXTERNAL_ACTION_COMMAND
SET OUTCOME_STATUS = CASE
        WHEN STATUS = 'SUCCEEDED' THEN 'SUCCEEDED'
        WHEN STATUS IN ('RETRY_WAIT', 'MANUAL_RETRY_REQUIRED') THEN 'FAILED'
        ELSE 'PENDING'
    END
WHERE OUTCOME_STATUS = 'PENDING';
