CREATE TABLE AGENT_ORDER_WRITE_RESERVATION (
    USER_ID VARCHAR(128) NOT NULL,
    ORDER_ID VARCHAR(128) NOT NULL,
    RUN_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_AGENT_ORDER_WRITE_RESERVATION PRIMARY KEY (USER_ID, ORDER_ID),
    CONSTRAINT UQ_AGENT_ORDER_WRITE_RESERVATION_RUN UNIQUE (RUN_ID),
    CONSTRAINT FK_AGENT_ORDER_WRITE_RESERVATION_RUN FOREIGN KEY (RUN_ID)
        REFERENCES AGENT_WORKFLOW_RUN (RUN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 兼容版本的未完成事项在切换时占位；同一订单的历史冲突只保留最早 Run，后续需人工盘点。
INSERT IGNORE INTO AGENT_ORDER_WRITE_RESERVATION (USER_ID, ORDER_ID, RUN_ID)
SELECT USER_ID, JSON_UNQUOTE(JSON_EXTRACT(STATE_JSON, '$.orderId')), RUN_ID
FROM AGENT_WORKFLOW_RUN
WHERE STATUS IN ('WAITING_USER_INPUT', 'WAITING_EXTERNAL_ACTION', 'MANUAL_RETRY_REQUIRED')
  AND JSON_VALID(STATE_JSON)
  AND JSON_UNQUOTE(JSON_EXTRACT(STATE_JSON, '$.orderId')) IS NOT NULL
  AND JSON_UNQUOTE(JSON_EXTRACT(STATE_JSON, '$.orderId')) <> ''
ORDER BY CREATED_AT, RUN_ID;
