ALTER TABLE AGENT_TURN
    ADD COLUMN EXECUTION_SEMANTICS_VERSION INT NOT NULL DEFAULT 0 AFTER VERSION_NO;

CREATE TABLE AGENT_TURN_EXECUTION_STATE (
    TURN_ID VARCHAR(64) NOT NULL,
    ACTIVE_DURATION_MILLIS BIGINT NOT NULL DEFAULT 0,
    ACTIVE_TOOL_BATCH_ID VARCHAR(64) DEFAULT NULL,
    NEXT_TOOL_INDEX INT NOT NULL DEFAULT 0,
    TOOL_CALLS_JSON LONGTEXT NOT NULL,
    VERSION_NO BIGINT NOT NULL DEFAULT 0,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_AGENT_TURN_EXECUTION_STATE PRIMARY KEY (TURN_ID),
    CONSTRAINT FK_AGENT_TURN_EXECUTION_STATE_TURN FOREIGN KEY (TURN_ID)
        REFERENCES AGENT_TURN (TURN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
