CREATE TABLE AGENT_TURN_RESUME_SIGNAL (
    SIGNAL_ID VARCHAR(64) NOT NULL,
    TURN_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    REQUEST_ID VARCHAR(128) NOT NULL,
    SIGNAL_KIND VARCHAR(32) NOT NULL,
    INTERACTION_ID VARCHAR(128) DEFAULT NULL,
    EXPECTED_INTERACTION_VERSION BIGINT NOT NULL DEFAULT 0,
    PAYLOAD_JSON LONGTEXT NOT NULL,
    ITEM_ID VARCHAR(64) NOT NULL,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    VERSION_NO BIGINT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    APPLIED_AT TIMESTAMP(6) DEFAULT NULL,
    CONSTRAINT PK_AGENT_TURN_RESUME_SIGNAL PRIMARY KEY (SIGNAL_ID),
    CONSTRAINT UQ_AGENT_TURN_RESUME_REQUEST UNIQUE (USER_ID, REQUEST_ID),
    CONSTRAINT FK_AGENT_TURN_RESUME_SIGNAL_TURN FOREIGN KEY (TURN_ID)
        REFERENCES AGENT_TURN (TURN_ID),
    INDEX IDX_AGENT_TURN_RESUME_PENDING (USER_ID, TURN_ID, STATUS, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
