-- 订单搜索所需的展示摘要和隐藏时间；只增量补齐，不删除已有订单事实。
SET @cga_schema = DATABASE();

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'DEMO_ORDER'
           AND COLUMN_NAME = 'ITEM_SUMMARY') = 0,
        'ALTER TABLE DEMO_ORDER ADD COLUMN ITEM_SUMMARY VARCHAR(256) DEFAULT NULL AFTER CURRENCY',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'DEMO_ORDER'
           AND COLUMN_NAME = 'HIDDEN_AT') = 0,
        'ALTER TABLE DEMO_ORDER ADD COLUMN HIDDEN_AT DATETIME(6) DEFAULT NULL AFTER ITEM_SUMMARY',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

-- 仅补充不存在的演示订单，不更新或删除已有交易事实；真实业务库中的同名记录保持原样。
INSERT IGNORE INTO DEMO_ORDER (
    ORDER_ID, USER_ID, STATUS, DAYS_SINCE_DELIVERY, CREATED_AT, EXPECTED_DELIVERY_AT,
    LAST_LOGISTICS_AT, LOGISTICS_STATUS, PAID_AMOUNT, CURRENCY, ITEM_SUMMARY, HIDDEN_AT, UPDATED_AT
) VALUES
('ORDER-TODAY-PAID-001', 'demo-user-1', 'PAID', NULL,
 DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 3 HOUR), NULL, NULL, NULL, 39.90, 'CNY', '棉质家居拖鞋', NULL, CURRENT_TIMESTAMP(6)),
('ORDER-TODAY-DELIVERED-001', 'demo-user-1', 'DELIVERED', 0,
 DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 8 HOUR), DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 1 HOUR),
 DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 1 HOUR), 'DELIVERED', 199.00, 'CNY', '便携榨汁杯', NULL, CURRENT_TIMESTAMP(6)),
('ORDER-7D-DELIVERED-001', 'demo-user-1', 'DELIVERED', 2,
 DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 48 HOUR), DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 12 HOUR),
 DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 12 HOUR), 'DELIVERED', 599.00, 'CNY', '人体工学办公椅', NULL, CURRENT_TIMESTAMP(6)),
('ORDER-7D-CANCELLED-001', 'demo-user-1', 'CANCELLED', NULL,
 DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 120 HOUR), NULL, NULL, NULL, 59.00, 'CNY', '旅行收纳袋', NULL, CURRENT_TIMESTAMP(6)),
('ORDER-SHIPPED-OK-001', 'demo-user-1', 'SHIPPED', NULL,
 DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 144 HOUR), DATE_ADD(CURRENT_TIMESTAMP(6), INTERVAL 36 HOUR),
 DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 6 HOUR), 'IN_TRANSIT', 299.00, 'CNY', '智能台灯', NULL, CURRENT_TIMESTAMP(6)),
('ORDER-SHIPPED-STALLED-002', 'demo-user-1', 'SHIPPED', NULL,
 DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 168 HOUR), DATE_ADD(CURRENT_TIMESTAMP(6), INTERVAL 48 HOUR),
 DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 120 HOUR), 'IN_TRANSIT', 109.00, 'CNY', '户外保温水壶', NULL, CURRENT_TIMESTAMP(6));

INSERT IGNORE INTO DEMO_LOGISTICS_EVENT (EVENT_ID, ORDER_ID, STATUS, LOCATION, DESCRIPTION, OCCURRED_AT) VALUES
('LOG-TODAY-DELIVERED-001', 'ORDER-TODAY-DELIVERED-001', 'DELIVERED', '上海配送站', '包裹已送达。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 1 HOUR)),
('LOG-SHIPPED-OK-001', 'ORDER-SHIPPED-OK-001', 'IN_TRANSIT', '杭州转运中心', '包裹已进入下一站。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 6 HOUR)),
('LOG-SHIPPED-STALLED-002-001', 'ORDER-SHIPPED-STALLED-002', 'PICKED_UP', '北京分拨中心', '包裹已由承运商揽收。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 144 HOUR)),
('LOG-SHIPPED-STALLED-002-002', 'ORDER-SHIPPED-STALLED-002', 'IN_TRANSIT', '天津转运中心', '包裹正在转运。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 120 HOUR));

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.STATISTICS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'DEMO_ORDER'
           AND INDEX_NAME = 'IDX_DEMO_ORDER_USER_VISIBILITY_TIME') = 0,
        'ALTER TABLE DEMO_ORDER ADD INDEX IDX_DEMO_ORDER_USER_VISIBILITY_TIME (USER_ID, HIDDEN_AT, CREATED_AT)',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;
