-- 为同一 ORDER_SERVICE Run 持久化步骤快照，并允许依次产生多个 QuestionCard。
SET @cga_schema = DATABASE();

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_WORKFLOW_RUN'
           AND COLUMN_NAME = 'STEPS_JSON') = 0,
        'ALTER TABLE AGENT_WORKFLOW_RUN ADD COLUMN STEPS_JSON LONGTEXT NULL AFTER VERSION_NO',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_WORKFLOW_RUN'
           AND COLUMN_NAME = 'STATE_JSON') = 0,
        'ALTER TABLE AGENT_WORKFLOW_RUN ADD COLUMN STATE_JSON LONGTEXT NULL AFTER STEPS_JSON',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_WORKFLOW_QUESTION'
           AND COLUMN_NAME = 'STEP_NO') = 0,
        'ALTER TABLE AGENT_WORKFLOW_QUESTION ADD COLUMN STEP_NO INT NOT NULL DEFAULT 0 AFTER CHECKPOINT_ID',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

UPDATE AGENT_WORKFLOW_RUN
SET STEPS_JSON = COALESCE(NULLIF(STEPS_JSON, ''), '[]'),
    STATE_JSON = COALESCE(NULLIF(STATE_JSON, ''), '{}')
WHERE STEPS_JSON IS NULL OR STEPS_JSON = '' OR STATE_JSON IS NULL OR STATE_JSON = '';

ALTER TABLE AGENT_WORKFLOW_RUN
    MODIFY COLUMN STEPS_JSON LONGTEXT NOT NULL,
    MODIFY COLUMN STATE_JSON LONGTEXT NOT NULL;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
         WHERE CONSTRAINT_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_WORKFLOW_QUESTION'
           AND CONSTRAINT_NAME = 'FK_AGENT_WORKFLOW_QUESTION_RUN'
           AND CONSTRAINT_TYPE = 'FOREIGN KEY') > 0,
        'ALTER TABLE AGENT_WORKFLOW_QUESTION DROP FOREIGN KEY FK_AGENT_WORKFLOW_QUESTION_RUN',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.STATISTICS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_WORKFLOW_QUESTION'
           AND INDEX_NAME = 'UQ_AGENT_WORKFLOW_QUESTION_RUN') > 0,
        'ALTER TABLE AGENT_WORKFLOW_QUESTION DROP INDEX UQ_AGENT_WORKFLOW_QUESTION_RUN',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.STATISTICS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_WORKFLOW_QUESTION'
           AND INDEX_NAME = 'UQ_AGENT_WORKFLOW_QUESTION_RUN_STEP') = 0,
        'ALTER TABLE AGENT_WORKFLOW_QUESTION ADD UNIQUE INDEX UQ_AGENT_WORKFLOW_QUESTION_RUN_STEP (RUN_ID, STEP_NO)',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
         WHERE CONSTRAINT_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_WORKFLOW_QUESTION'
           AND CONSTRAINT_NAME = 'FK_AGENT_WORKFLOW_QUESTION_RUN'
           AND CONSTRAINT_TYPE = 'FOREIGN KEY') = 0,
        'ALTER TABLE AGENT_WORKFLOW_QUESTION ADD CONSTRAINT FK_AGENT_WORKFLOW_QUESTION_RUN FOREIGN KEY (RUN_ID) REFERENCES AGENT_WORKFLOW_RUN (RUN_ID)',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;
