-- 既有配置库可能停留在早期 Thread/Turn/ExternalAction 基线；只增量补齐当前代码依赖的事实字段和幂等约束。
SET @cga_schema = DATABASE();

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_THREAD'
           AND COLUMN_NAME = 'OPEN_QUESTION_ID') = 0,
        'ALTER TABLE AGENT_THREAD ADD COLUMN OPEN_QUESTION_ID VARCHAR(64) DEFAULT NULL AFTER CONTEXT_ID',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_TURN'
           AND COLUMN_NAME = 'WORKFLOW_QUESTION_ID') = 0,
        'ALTER TABLE AGENT_TURN ADD COLUMN WORKFLOW_QUESTION_ID VARCHAR(64) DEFAULT NULL AFTER WORKFLOW_RUN_ID',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_TURN'
           AND COLUMN_NAME = 'WORKFLOW_CHECKPOINT_ID') = 0,
        'ALTER TABLE AGENT_TURN ADD COLUMN WORKFLOW_CHECKPOINT_ID VARCHAR(128) DEFAULT NULL AFTER WORKFLOW_QUESTION_ID',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_TURN'
           AND COLUMN_NAME = 'WORKFLOW_QUESTION_VERSION') = 0,
        'ALTER TABLE AGENT_TURN ADD COLUMN WORKFLOW_QUESTION_VERSION BIGINT DEFAULT NULL AFTER WORKFLOW_CHECKPOINT_ID',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_TURN'
           AND COLUMN_NAME = 'WORKFLOW_ANSWERS_JSON') = 0,
        'ALTER TABLE AGENT_TURN ADD COLUMN WORKFLOW_ANSWERS_JSON LONGTEXT DEFAULT NULL AFTER WORKFLOW_QUESTION_VERSION',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_TURN'
           AND COLUMN_NAME = 'VERSION_NO') = 0,
        'ALTER TABLE AGENT_TURN ADD COLUMN VERSION_NO BIGINT NOT NULL DEFAULT 0 AFTER FINISHED_AT',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'EXTERNAL_ACTION_COMMAND'
           AND COLUMN_NAME = 'VERSION_NO') = 0,
        'ALTER TABLE EXTERNAL_ACTION_COMMAND ADD COLUMN VERSION_NO BIGINT NOT NULL DEFAULT 0 AFTER PAYLOAD_JSON',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'EXTERNAL_ACTION_COMMAND'
           AND COLUMN_NAME = 'RETRY_CYCLE_ATTEMPT_COUNT') = 0,
        'ALTER TABLE EXTERNAL_ACTION_COMMAND ADD COLUMN RETRY_CYCLE_ATTEMPT_COUNT INT NOT NULL DEFAULT 0 AFTER MAX_ATTEMPTS',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

-- 旧基线将该字段声明为 NOT NULL，但新建命令允许尚未安排下一次重试的 NULL 值。
ALTER TABLE EXTERNAL_ACTION_COMMAND
    MODIFY COLUMN NEXT_ATTEMPT_AT DATETIME(6) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS EXTERNAL_ACTION_RESULT (
    RESULT_ID VARCHAR(64) NOT NULL,
    COMMAND_ID VARCHAR(64) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(256) NOT NULL,
    ACTION_TYPE VARCHAR(32) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    RESPONSE_JSON LONGTEXT NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_EXTERNAL_ACTION_RESULT PRIMARY KEY (RESULT_ID),
    CONSTRAINT UQ_EXTERNAL_ACTION_RESULT_COMMAND UNIQUE (COMMAND_ID),
    CONSTRAINT UQ_EXTERNAL_ACTION_RESULT_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT FK_EXTERNAL_ACTION_RESULT_COMMAND FOREIGN KEY (COMMAND_ID) REFERENCES EXTERNAL_ACTION_COMMAND (COMMAND_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.STATISTICS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_WORKFLOW_RUN'
           AND INDEX_NAME = 'UQ_AGENT_WORKFLOW_RUN_SOURCE') = 0,
        'ALTER TABLE AGENT_WORKFLOW_RUN ADD UNIQUE INDEX UQ_AGENT_WORKFLOW_RUN_SOURCE (USER_ID, TURN_ID, WORKFLOW_TYPE)',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.STATISTICS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_WORKFLOW_QUESTION'
           AND INDEX_NAME = 'UQ_AGENT_WORKFLOW_QUESTION_ANSWER_TURN') = 0,
        'ALTER TABLE AGENT_WORKFLOW_QUESTION ADD UNIQUE INDEX UQ_AGENT_WORKFLOW_QUESTION_ANSWER_TURN (ANSWER_TURN_ID)',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;
