-- 持久化确定性订单动作 Turn；历史 WORKFLOW_ANSWER 仅供 V9 迁移识别，运行时不再创建。
SET @cga_schema = DATABASE();

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_TURN'
           AND COLUMN_NAME = 'INPUT_KIND') = 0,
        'ALTER TABLE AGENT_TURN ADD COLUMN INPUT_KIND VARCHAR(32) NOT NULL DEFAULT ''MESSAGE'' AFTER INPUT_TEXT',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

SET @cga_sql = IF(
        (SELECT COUNT(*)
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_SCHEMA = @cga_schema
           AND TABLE_NAME = 'AGENT_TURN'
           AND COLUMN_NAME = 'ORDER_ACTION_JSON') = 0,
        'ALTER TABLE AGENT_TURN ADD COLUMN ORDER_ACTION_JSON LONGTEXT DEFAULT NULL AFTER INPUT_KIND',
        'SELECT 1');
PREPARE cga_statement FROM @cga_sql;
EXECUTE cga_statement;
DEALLOCATE PREPARE cga_statement;

UPDATE AGENT_TURN
SET INPUT_KIND = 'WORKFLOW_ANSWER'
WHERE INPUT_KIND = 'MESSAGE'
  AND WORKFLOW_ANSWERS_JSON IS NOT NULL;
