-- LangGraph 技术快照仅用于恢复图执行，不承载业务授权或业务状态事实。
CREATE TABLE IF NOT EXISTS AGENT_GRAPH_SNAPSHOT (
    SNAPSHOT_ID VARCHAR(64) NOT NULL,
    RUN_ID VARCHAR(64) NOT NULL,
    GRAPH_THREAD_ID VARCHAR(64) NOT NULL,
    CHECKPOINT_ID VARCHAR(128) NOT NULL,
    NODE_ID VARCHAR(128) NOT NULL,
    NEXT_NODE_ID VARCHAR(128) DEFAULT NULL,
    STATE_JSON LONGTEXT NOT NULL,
    WORKFLOW_VERSION BIGINT NOT NULL,
    FACTS_FINGERPRINT VARCHAR(128) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_AGENT_GRAPH_SNAPSHOT PRIMARY KEY (SNAPSHOT_ID),
    CONSTRAINT UQ_AGENT_GRAPH_SNAPSHOT_CHECKPOINT UNIQUE (GRAPH_THREAD_ID, CHECKPOINT_ID),
    CONSTRAINT FK_AGENT_GRAPH_SNAPSHOT_RUN FOREIGN KEY (RUN_ID) REFERENCES AGENT_WORKFLOW_RUN (RUN_ID),
    INDEX IDX_AGENT_GRAPH_SNAPSHOT_LATEST (GRAPH_THREAD_ID, UPDATED_AT DESC),
    INDEX IDX_AGENT_GRAPH_SNAPSHOT_RUN (RUN_ID, WORKFLOW_VERSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- V8 不回填历史快照；业务 WorkflowRun 可在第一次恢复时重建技术状态。
