-- V9 将“询问用户”和“确认固定 Workflow 执行”拆为独立业务事实。
-- 旧 AGENT_WORKFLOW_QUESTION 只作为迁移来源，保留期内由运行时代码只读。
ALTER TABLE AGENT_THREAD
    ADD COLUMN OPEN_INTERACTION_TYPE VARCHAR(32) DEFAULT NULL AFTER OPEN_QUESTION_ID,
    ADD COLUMN OPEN_INTERACTION_ID VARCHAR(64) DEFAULT NULL AFTER OPEN_INTERACTION_TYPE;

ALTER TABLE AGENT_TURN
    ADD COLUMN QUESTION_CARD_ID VARCHAR(64) DEFAULT NULL AFTER WORKFLOW_QUESTION_ID,
    ADD COLUMN QUESTION_ANSWER_JSON LONGTEXT DEFAULT NULL AFTER WORKFLOW_ANSWERS_JSON,
    ADD COLUMN WORKFLOW_DECISION_JSON LONGTEXT DEFAULT NULL AFTER QUESTION_ANSWER_JSON;

CREATE TABLE IF NOT EXISTS AGENT_QUESTION_CARD (
    QUESTION_ID VARCHAR(64) NOT NULL,
    RUN_ID VARCHAR(64) DEFAULT NULL,
    THREAD_ID VARCHAR(64) NOT NULL,
    TURN_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    RESUME_TARGET VARCHAR(16) NOT NULL,
    STEP_NO INT NOT NULL DEFAULT 0,
    VERSION_NO BIGINT NOT NULL DEFAULT 0,
    ANSWER_TURN_ID VARCHAR(64) DEFAULT NULL,
    ANSWER_ENQUEUE_STATUS VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
    TITLE VARCHAR(256) NOT NULL,
    PROMPT VARCHAR(2000) NOT NULL,
    FIELDS_JSON LONGTEXT NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    ANSWERED_AT DATETIME(6) DEFAULT NULL,
    CONSTRAINT PK_AGENT_QUESTION_CARD PRIMARY KEY (QUESTION_ID),
    CONSTRAINT FK_AGENT_QUESTION_CARD_THREAD FOREIGN KEY (THREAD_ID) REFERENCES AGENT_THREAD (THREAD_ID),
    CONSTRAINT FK_AGENT_QUESTION_CARD_RUN FOREIGN KEY (RUN_ID) REFERENCES AGENT_WORKFLOW_RUN (RUN_ID),
    CONSTRAINT UQ_AGENT_QUESTION_CARD_ANSWER_TURN UNIQUE (ANSWER_TURN_ID),
    INDEX IDX_AGENT_QUESTION_CARD_OPEN (USER_ID, THREAD_ID, STATUS),
    INDEX IDX_AGENT_QUESTION_CARD_RUN_STEP (RUN_ID, STEP_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS AGENT_WORKFLOW_CHECKPOINT (
    CHECKPOINT_ID VARCHAR(128) NOT NULL,
    RUN_ID VARCHAR(64) NOT NULL,
    THREAD_ID VARCHAR(64) NOT NULL,
    TURN_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    NODE_ID VARCHAR(128) NOT NULL,
    ACTION_TYPE VARCHAR(64) NOT NULL,
    ORDER_ID VARCHAR(64) NOT NULL,
    IMPACT_SUMMARY VARCHAR(2000) NOT NULL,
    FACTS_FINGERPRINT VARCHAR(128) NOT NULL,
    VERSION_NO BIGINT NOT NULL DEFAULT 0,
    STATUS VARCHAR(32) NOT NULL,
    DECISION VARCHAR(16) DEFAULT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    DECIDED_AT DATETIME(6) DEFAULT NULL,
    CONSTRAINT PK_AGENT_WORKFLOW_CHECKPOINT PRIMARY KEY (CHECKPOINT_ID),
    CONSTRAINT FK_AGENT_WORKFLOW_CHECKPOINT_RUN FOREIGN KEY (RUN_ID) REFERENCES AGENT_WORKFLOW_RUN (RUN_ID),
    CONSTRAINT FK_AGENT_WORKFLOW_CHECKPOINT_THREAD FOREIGN KEY (THREAD_ID) REFERENCES AGENT_THREAD (THREAD_ID),
    INDEX IDX_AGENT_WORKFLOW_CHECKPOINT_OPEN (USER_ID, THREAD_ID, STATUS),
    INDEX IDX_AGENT_WORKFLOW_CHECKPOINT_RUN (USER_ID, RUN_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 普通历史问题进入 QuestionCard，恢复到原有 Workflow；不再把普通问题当成授权。
INSERT IGNORE INTO AGENT_QUESTION_CARD (
    QUESTION_ID, RUN_ID, THREAD_ID, TURN_ID, USER_ID, RESUME_TARGET, STEP_NO, VERSION_NO,
    ANSWER_TURN_ID, ANSWER_ENQUEUE_STATUS, TITLE, PROMPT, FIELDS_JSON, STATUS, CREATED_AT, ANSWERED_AT
)
SELECT QUESTION_ID, RUN_ID, THREAD_ID, TURN_ID, USER_ID, 'WORKFLOW', COALESCE(STEP_NO, 0), COALESCE(VERSION_NO, 0),
       ANSWER_TURN_ID, COALESCE(ANSWER_ENQUEUE_STATUS, 'AVAILABLE'), TITLE, PROMPT, FIELDS_JSON,
       STATUS, CREATED_AT, ANSWERED_AT
FROM AGENT_WORKFLOW_QUESTION
WHERE FIELDS_JSON NOT LIKE '%AUTHORIZATION%';

-- 历史授权问题进入独立 Checkpoint；已回答的历史不凭空补发批准，标记为 SUPERSEDED。
INSERT IGNORE INTO AGENT_WORKFLOW_CHECKPOINT (
    CHECKPOINT_ID, RUN_ID, THREAD_ID, TURN_ID, USER_ID, NODE_ID, ACTION_TYPE, ORDER_ID,
    IMPACT_SUMMARY, FACTS_FINGERPRINT, VERSION_NO, STATUS, DECISION, CREATED_AT, DECIDED_AT
)
SELECT q.CHECKPOINT_ID, q.RUN_ID, q.THREAD_ID, q.TURN_ID, q.USER_ID, 'AUTHORIZE', 'LEGACY_WORKFLOW_WRITE',
       COALESCE(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(r.STATE_JSON, '$.orderId')), ''), 'UNKNOWN'),
       LEFT(q.PROMPT, 2000), SHA2(CONCAT(q.QUESTION_ID, ':', q.VERSION_NO, ':', q.FIELDS_JSON), 256),
       COALESCE(q.VERSION_NO, 0),
       CASE WHEN q.STATUS = 'OPEN' THEN 'OPEN' ELSE 'SUPERSEDED' END,
       NULL, q.CREATED_AT, CASE WHEN q.STATUS = 'OPEN' THEN NULL ELSE q.ANSWERED_AT END
FROM AGENT_WORKFLOW_QUESTION q
JOIN AGENT_WORKFLOW_RUN r ON r.RUN_ID = q.RUN_ID
WHERE q.FIELDS_JSON LIKE '%AUTHORIZATION%';

-- 同一 Thread 只保留一个开放交互引用；旧授权问题的开放引用指向 Checkpoint。
UPDATE AGENT_THREAD t
LEFT JOIN AGENT_WORKFLOW_QUESTION q ON q.QUESTION_ID = t.OPEN_QUESTION_ID
SET t.OPEN_INTERACTION_TYPE = CASE WHEN q.FIELDS_JSON LIKE '%AUTHORIZATION%'
                                   THEN 'WORKFLOW_CHECKPOINT' ELSE 'QUESTION_CARD' END,
    t.OPEN_INTERACTION_ID = t.OPEN_QUESTION_ID
WHERE t.OPEN_QUESTION_ID IS NOT NULL;
