-- AI Agent Station 首版初始化脚本。
-- 初始化演示订单、可恢复 Workflow、退款和会话记忆对象；不会删除任何旧表。
CREATE DATABASE IF NOT EXISTS AI_AGENT_STATION CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE AI_AGENT_STATION;

CREATE TABLE IF NOT EXISTS DEMO_ORDER (
    ORDER_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(64) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    DAYS_SINCE_DELIVERY INT DEFAULT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    EXPECTED_DELIVERY_AT DATETIME(6) DEFAULT NULL,
    LAST_LOGISTICS_AT DATETIME(6) DEFAULT NULL,
    LOGISTICS_STATUS VARCHAR(32) DEFAULT NULL,
    PAID_AMOUNT DECIMAL(19, 2) DEFAULT NULL,
    CURRENCY VARCHAR(8) DEFAULT NULL,
    UPDATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT PK_DEMO_ORDER PRIMARY KEY (ORDER_ID),
    INDEX IDX_DEMO_ORDER_USER_STATUS (USER_ID, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS DEMO_ORDER_ITEM (
    ITEM_ID VARCHAR(64) NOT NULL,
    ORDER_ID VARCHAR(64) NOT NULL,
    PRODUCT_NAME VARCHAR(256) NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(19, 2) NOT NULL,
    CONSTRAINT PK_DEMO_ORDER_ITEM PRIMARY KEY (ITEM_ID),
    INDEX IDX_DEMO_ORDER_ITEM_ORDER (ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS DEMO_LOGISTICS_EVENT (
    EVENT_ID VARCHAR(64) NOT NULL,
    ORDER_ID VARCHAR(64) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    LOCATION VARCHAR(256) DEFAULT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    OCCURRED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_DEMO_LOGISTICS_EVENT PRIMARY KEY (EVENT_ID),
    INDEX IDX_DEMO_LOGISTICS_EVENT_ORDER_TIME (ORDER_ID, OCCURRED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS WORKFLOW_RUN (
    RUN_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    SESSION_ID VARCHAR(128) NOT NULL,
    DOMAIN_ID VARCHAR(64) NOT NULL,
    WORKFLOW_ID VARCHAR(128) NOT NULL,
    WORKFLOW_VERSION VARCHAR(32) NOT NULL,
    OPERATION VARCHAR(64) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    CHECKPOINT_ID VARCHAR(128) NOT NULL,
    VERSION BIGINT NOT NULL,
    STATE_JSON LONGTEXT NOT NULL,
    QUESTION_JSON LONGTEXT DEFAULT NULL,
    RESULT_CONTENT VARCHAR(2000) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_WORKFLOW_RUN PRIMARY KEY (RUN_ID),
    INDEX IDX_WORKFLOW_RUN_OWNER (USER_ID, SESSION_ID, UPDATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS WORKFLOW_RUN_EVENT (
    EVENT_ID VARCHAR(64) NOT NULL,
    RUN_ID VARCHAR(64) NOT NULL,
    VERSION BIGINT NOT NULL,
    EVENT_TYPE VARCHAR(64) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    CHECKPOINT_ID VARCHAR(128) NOT NULL,
    OCCURRED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_WORKFLOW_RUN_EVENT PRIMARY KEY (EVENT_ID),
    INDEX IDX_WORKFLOW_RUN_EVENT_RUN_VERSION (RUN_ID, VERSION),
    CONSTRAINT FK_WORKFLOW_RUN_EVENT_RUN FOREIGN KEY (RUN_ID) REFERENCES WORKFLOW_RUN (RUN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS DEMO_REFUND_COMMAND (
    REFUND_ID VARCHAR(64) NOT NULL,
    WORKFLOW_RUN_ID VARCHAR(64) NOT NULL,
    CASE_ID VARCHAR(64) NOT NULL,
    ORDER_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(64) NOT NULL,
    REFUND_REASON VARCHAR(32) NOT NULL,
    AMOUNT DECIMAL(19, 2) NOT NULL,
    CURRENCY VARCHAR(8) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    RETRY_ID VARCHAR(128) NOT NULL DEFAULT '',
    ATTEMPT_COUNT INT NOT NULL DEFAULT 0,
    NEXT_ATTEMPT_AT DATETIME(6) NOT NULL,
    LEASE_UNTIL DATETIME(6) DEFAULT NULL,
    FAILURE_CODE VARCHAR(64) NOT NULL DEFAULT '',
    VERSION BIGINT NOT NULL DEFAULT 0,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_DEMO_REFUND_COMMAND PRIMARY KEY (REFUND_ID),
    CONSTRAINT UK_DEMO_REFUND_COMMAND_RUN UNIQUE (WORKFLOW_RUN_ID),
    CONSTRAINT UK_DEMO_REFUND_COMMAND_CASE UNIQUE (CASE_ID),
    INDEX IDX_DEMO_REFUND_COMMAND_ORDER_USER (ORDER_ID, USER_ID, CREATED_AT),
    INDEX IDX_DEMO_REFUND_COMMAND_DUE (STATUS, NEXT_ATTEMPT_AT, LEASE_UNTIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS DEMO_AFTER_SALES_CASE (
    CASE_ID VARCHAR(64) NOT NULL,
    WORKFLOW_RUN_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(64) NOT NULL,
    ORDER_ID VARCHAR(64) NOT NULL,
    REQUEST_TYPE VARCHAR(32) NOT NULL,
    REFUND_REASON VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL DEFAULT '',
    HANDLING_MODE VARCHAR(32) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    AMOUNT DECIMAL(19, 2) DEFAULT NULL,
    CURRENCY VARCHAR(8) NOT NULL DEFAULT '',
    REFUND_ID VARCHAR(64) NOT NULL DEFAULT '',
    OPERATOR_ID VARCHAR(128) NOT NULL DEFAULT '',
    DECISION_ID VARCHAR(128) NOT NULL DEFAULT '',
    DECISION_NOTE VARCHAR(500) NOT NULL DEFAULT '',
    REVIEWED_AT DATETIME(6) DEFAULT NULL,
    FAILURE_CODE VARCHAR(64) NOT NULL DEFAULT '',
    VERSION BIGINT NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_DEMO_AFTER_SALES_CASE PRIMARY KEY (CASE_ID),
    CONSTRAINT UK_DEMO_AFTER_SALES_CASE_RUN UNIQUE (WORKFLOW_RUN_ID),
    CONSTRAINT UK_DEMO_AFTER_SALES_CASE_ORDER UNIQUE (USER_ID, ORDER_ID, REQUEST_TYPE),
    INDEX IDX_DEMO_AFTER_SALES_CASE_ORDER (ORDER_ID, USER_ID, UPDATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS AI_SESSION (
    ID VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    EXPIRES_AT DATETIME(6) DEFAULT NULL,
    METADATA LONGTEXT,
    EVENT_VERSION BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT PK_AI_SESSION PRIMARY KEY (ID),
    INDEX IDX_AI_SESSION_USER_ID (USER_ID),
    INDEX IDX_AI_SESSION_EXPIRES_AT (EXPIRES_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS AI_SESSION_EVENT (
    ID VARCHAR(255) NOT NULL,
    SESSION_ID VARCHAR(255) NOT NULL,
    TIMESTAMP DATETIME(6) NOT NULL,
    MESSAGE_TYPE VARCHAR(20) NOT NULL,
    MESSAGE_CONTENT LONGTEXT,
    MESSAGE_DATA LONGTEXT,
    SYNTHETIC TINYINT(1) NOT NULL DEFAULT 0,
    BRANCH VARCHAR(500) DEFAULT NULL,
    METADATA LONGTEXT,
    CONSTRAINT PK_AI_SESSION_EVENT PRIMARY KEY (ID),
    INDEX IDX_AI_SESSION_EVENT_SESSION_TS (SESSION_ID, TIMESTAMP),
    CONSTRAINT FK_AI_SESSION_EVENT_SESSION FOREIGN KEY (SESSION_ID) REFERENCES AI_SESSION (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS AGENT_MEMORY_SOURCE (
    SOURCE_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    SESSION_ID VARCHAR(128) NOT NULL,
    REQUEST_ID VARCHAR(128) NOT NULL,
    SOURCE_TYPE VARCHAR(32) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_AGENT_MEMORY_SOURCE PRIMARY KEY (SOURCE_ID),
    INDEX IDX_AGENT_MEMORY_SOURCE_SESSION (USER_ID, SESSION_ID, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS AGENT_MEMORY_ENTRY (
    ENTRY_ID VARCHAR(64) NOT NULL,
    SOURCE_ID VARCHAR(64) DEFAULT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    SESSION_ID VARCHAR(128) NOT NULL,
    CATEGORY VARCHAR(32) NOT NULL,
    MEMORY_KEY VARCHAR(64) NOT NULL,
    MEMORY_VALUE VARCHAR(512) NOT NULL,
    ORIGIN VARCHAR(32) NOT NULL,
    CONFIDENCE DECIMAL(4,3) NOT NULL,
    VERSION BIGINT NOT NULL DEFAULT 0,
    DELETED TINYINT(1) NOT NULL DEFAULT 0,
    EXPIRES_AT DATETIME(6) DEFAULT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_AGENT_MEMORY_ENTRY PRIMARY KEY (ENTRY_ID),
    CONSTRAINT FK_AGENT_MEMORY_ENTRY_SOURCE FOREIGN KEY (SOURCE_ID) REFERENCES AGENT_MEMORY_SOURCE (SOURCE_ID),
    CONSTRAINT UQ_AGENT_MEMORY_ENTRY_OWNER_KEY UNIQUE (USER_ID, SESSION_ID, CATEGORY, MEMORY_KEY),
    INDEX IDX_AGENT_MEMORY_ENTRY_OWNER (USER_ID, SESSION_ID, DELETED, UPDATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS AGENT_MEMORY_EVIDENCE (
    EVIDENCE_ID VARCHAR(64) NOT NULL,
    ENTRY_ID VARCHAR(64) NOT NULL,
    EVIDENCE_TYPE VARCHAR(32) NOT NULL,
    EVIDENCE_REF VARCHAR(512) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_AGENT_MEMORY_EVIDENCE PRIMARY KEY (EVIDENCE_ID),
    CONSTRAINT FK_AGENT_MEMORY_EVIDENCE_ENTRY FOREIGN KEY (ENTRY_ID) REFERENCES AGENT_MEMORY_ENTRY (ENTRY_ID),
    INDEX IDX_AGENT_MEMORY_EVIDENCE_ENTRY (ENTRY_ID, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO DEMO_ORDER (
    ORDER_ID, USER_ID, STATUS, DAYS_SINCE_DELIVERY, CREATED_AT,
    EXPECTED_DELIVERY_AT, LAST_LOGISTICS_AT, LOGISTICS_STATUS, PAID_AMOUNT, CURRENCY
) VALUES
    (
        'ORDER-PAID-001', 'demo-user-1', 'PAID', NULL,
        DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 72 HOUR), NULL, NULL, NULL, 99.00, 'CNY'
    ),
    (
        'ORDER-SHIPPED-OVERDUE-001', 'demo-user-1', 'SHIPPED', NULL,
        DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 120 HOUR),
        DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 24 HOUR),
        DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 12 HOUR), 'DELIVERING', 129.00, 'CNY'
    ),
    (
        'ORDER-SHIPPED-STALLED-001', 'demo-user-1', 'SHIPPED', NULL,
        DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 120 HOUR),
        DATE_ADD(CURRENT_TIMESTAMP(6), INTERVAL 24 HOUR),
        DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 72 HOUR), 'IN_TRANSIT', 129.00, 'CNY'
    ),
    (
        'ORDER-DELIVERED-001', 'demo-user-1', 'DELIVERED', 3,
        DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 96 HOUR), NULL,
        DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 72 HOUR), 'SIGNED', 199.00, 'CNY'
    ),
    (
        'ORDER-FOREIGN-001', 'demo-user-2', 'PAID', NULL,
        DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 72 HOUR), NULL, NULL, NULL, 88.00, 'CNY'
    )
ON DUPLICATE KEY UPDATE
    USER_ID = VALUES(USER_ID),
    STATUS = VALUES(STATUS),
    DAYS_SINCE_DELIVERY = VALUES(DAYS_SINCE_DELIVERY),
    CREATED_AT = VALUES(CREATED_AT),
    EXPECTED_DELIVERY_AT = VALUES(EXPECTED_DELIVERY_AT),
    LAST_LOGISTICS_AT = VALUES(LAST_LOGISTICS_AT),
    LOGISTICS_STATUS = VALUES(LOGISTICS_STATUS),
    PAID_AMOUNT = VALUES(PAID_AMOUNT),
    CURRENCY = VALUES(CURRENCY);

INSERT INTO DEMO_ORDER_ITEM (ITEM_ID, ORDER_ID, PRODUCT_NAME, QUANTITY, UNIT_PRICE) VALUES
    ('ITEM-PAID-001', 'ORDER-PAID-001', '演示蓝牙耳机', 1, 99.00),
    ('ITEM-OVERDUE-001', 'ORDER-SHIPPED-OVERDUE-001', '演示机械键盘', 1, 129.00),
    ('ITEM-STALLED-001', 'ORDER-SHIPPED-STALLED-001', '演示机械键盘', 1, 129.00),
    ('ITEM-DELIVERED-001', 'ORDER-DELIVERED-001', '演示显示器支架', 1, 199.00),
    ('ITEM-FOREIGN-001', 'ORDER-FOREIGN-001', '演示鼠标', 1, 88.00)
ON DUPLICATE KEY UPDATE
    PRODUCT_NAME = VALUES(PRODUCT_NAME),
    QUANTITY = VALUES(QUANTITY),
    UNIT_PRICE = VALUES(UNIT_PRICE);

INSERT INTO DEMO_LOGISTICS_EVENT (EVENT_ID, ORDER_ID, STATUS, LOCATION, DESCRIPTION, OCCURRED_AT) VALUES
    ('LOG-OVERDUE-001', 'ORDER-SHIPPED-OVERDUE-001', 'PICKED_UP', '上海分拨中心', '包裹已由承运商揽收。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 96 HOUR)),
    ('LOG-OVERDUE-002', 'ORDER-SHIPPED-OVERDUE-001', 'DELIVERING', '杭州配送站', '包裹正在配送。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 12 HOUR)),
    ('LOG-STALLED-001', 'ORDER-SHIPPED-STALLED-001', 'PICKED_UP', '深圳分拨中心', '包裹已由承运商揽收。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 96 HOUR)),
    ('LOG-STALLED-002', 'ORDER-SHIPPED-STALLED-001', 'IN_TRANSIT', '广州转运中心', '包裹正在转运。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 72 HOUR)),
    ('LOG-DELIVERED-001', 'ORDER-DELIVERED-001', 'SIGNED', '用户签收地址', '包裹已签收。', DATE_SUB(CURRENT_TIMESTAMP(6), INTERVAL 72 HOUR))
ON DUPLICATE KEY UPDATE
    STATUS = VALUES(STATUS),
    LOCATION = VALUES(LOCATION),
    DESCRIPTION = VALUES(DESCRIPTION),
    OCCURRED_AT = VALUES(OCCURRED_AT);
