-- Session Memory V2 升级脚本。先完成 QuestionCard/Memory V1 升级并备份后再执行。
USE AI_AGENT_STATION;

ALTER TABLE AGENT_MEMORY_ENTRY MODIFY COLUMN SOURCE_ID VARCHAR(64) DEFAULT NULL;
ALTER TABLE AGENT_MEMORY_ENTRY ADD COLUMN CATEGORY VARCHAR(32) DEFAULT NULL AFTER SESSION_ID;
ALTER TABLE AGENT_MEMORY_ENTRY ADD COLUMN MEMORY_KEY VARCHAR(64) DEFAULT NULL AFTER CATEGORY;
ALTER TABLE AGENT_MEMORY_ENTRY ADD COLUMN MEMORY_VALUE VARCHAR(512) DEFAULT NULL AFTER MEMORY_KEY;
ALTER TABLE AGENT_MEMORY_ENTRY ADD COLUMN ORIGIN VARCHAR(32) DEFAULT NULL AFTER MEMORY_VALUE;
ALTER TABLE AGENT_MEMORY_ENTRY ADD COLUMN CONFIDENCE DECIMAL(4,3) DEFAULT NULL AFTER ORIGIN;
ALTER TABLE AGENT_MEMORY_ENTRY ADD COLUMN EXPIRES_AT DATETIME(6) DEFAULT NULL AFTER DELETED;

-- V1 记录是完整最终答复，不能安全注入模型；软删除保留审计。
UPDATE AGENT_MEMORY_ENTRY
SET CATEGORY = 'LEGACY',
    MEMORY_KEY = CONCAT('legacy.', ENTRY_ID),
    MEMORY_VALUE = LEFT(CONTENT, 512),
    ORIGIN = 'LEGACY',
    CONFIDENCE = 0.000,
    DELETED = 1
WHERE CATEGORY IS NULL;

-- V2 插入只写结构化 MEMORY_VALUE，保留旧 CONTENT 仅用于审计。
ALTER TABLE AGENT_MEMORY_ENTRY MODIFY COLUMN CONTENT VARCHAR(4000) DEFAULT NULL;
ALTER TABLE AGENT_MEMORY_ENTRY MODIFY COLUMN CATEGORY VARCHAR(32) NOT NULL;
ALTER TABLE AGENT_MEMORY_ENTRY MODIFY COLUMN MEMORY_KEY VARCHAR(64) NOT NULL;
ALTER TABLE AGENT_MEMORY_ENTRY MODIFY COLUMN MEMORY_VALUE VARCHAR(512) NOT NULL;
ALTER TABLE AGENT_MEMORY_ENTRY MODIFY COLUMN ORIGIN VARCHAR(32) NOT NULL;
ALTER TABLE AGENT_MEMORY_ENTRY MODIFY COLUMN CONFIDENCE DECIMAL(4,3) NOT NULL;
ALTER TABLE AGENT_MEMORY_ENTRY ADD CONSTRAINT UQ_AGENT_MEMORY_ENTRY_OWNER_KEY
    UNIQUE (USER_ID, SESSION_ID, CATEGORY, MEMORY_KEY);
ALTER TABLE AGENT_MEMORY_ENTRY ADD INDEX IDX_AGENT_MEMORY_ENTRY_OWNER_V2
    (USER_ID, SESSION_ID, DELETED, UPDATED_AT);
