-- 订单诊断字段人工升级脚本。
-- 兼容不支持 ADD COLUMN IF NOT EXISTS 的 MySQL 8.x；不删除、重命名或重建任何现有表。
USE AI_AGENT_STATION;

SET @ADD_EXPECTED_DELIVERY_AT = (
    SELECT CASE WHEN EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'AI_AGENT_STATION'
          AND TABLE_NAME = 'DEMO_ORDER'
          AND COLUMN_NAME = 'EXPECTED_DELIVERY_AT'
    ) THEN 'SELECT 1'
    ELSE 'ALTER TABLE DEMO_ORDER ADD COLUMN EXPECTED_DELIVERY_AT DATETIME(6) DEFAULT NULL AFTER CREATED_AT'
    END
);
PREPARE ADD_EXPECTED_DELIVERY_AT FROM @ADD_EXPECTED_DELIVERY_AT;
EXECUTE ADD_EXPECTED_DELIVERY_AT;
DEALLOCATE PREPARE ADD_EXPECTED_DELIVERY_AT;

SET @ADD_LAST_LOGISTICS_AT = (
    SELECT CASE WHEN EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'AI_AGENT_STATION'
          AND TABLE_NAME = 'DEMO_ORDER'
          AND COLUMN_NAME = 'LAST_LOGISTICS_AT'
    ) THEN 'SELECT 1'
    ELSE 'ALTER TABLE DEMO_ORDER ADD COLUMN LAST_LOGISTICS_AT DATETIME(6) DEFAULT NULL AFTER EXPECTED_DELIVERY_AT'
    END
);
PREPARE ADD_LAST_LOGISTICS_AT FROM @ADD_LAST_LOGISTICS_AT;
EXECUTE ADD_LAST_LOGISTICS_AT;
DEALLOCATE PREPARE ADD_LAST_LOGISTICS_AT;

SET @ADD_LOGISTICS_STATUS = (
    SELECT CASE WHEN EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'AI_AGENT_STATION'
          AND TABLE_NAME = 'DEMO_ORDER'
          AND COLUMN_NAME = 'LOGISTICS_STATUS'
    ) THEN 'SELECT 1'
    ELSE 'ALTER TABLE DEMO_ORDER ADD COLUMN LOGISTICS_STATUS VARCHAR(32) DEFAULT NULL AFTER LAST_LOGISTICS_AT'
    END
);
PREPARE ADD_LOGISTICS_STATUS FROM @ADD_LOGISTICS_STATUS;
EXECUTE ADD_LOGISTICS_STATUS;
DEALLOCATE PREPARE ADD_LOGISTICS_STATUS;
