-- 为已有首版库增加退款 Workflow 所需对象；执行前请完成数据库备份。
USE AI_AGENT_STATION;

ALTER TABLE DEMO_ORDER
    ADD COLUMN PAID_AMOUNT DECIMAL(19, 2) DEFAULT NULL,
    ADD COLUMN CURRENCY VARCHAR(8) DEFAULT NULL;

-- 随后重新执行完整 ai-agent-station.sql。它使用 CREATE TABLE IF NOT EXISTS，
-- 只会补齐 WORKFLOW_RUN、WORKFLOW_RUN_EVENT、DEMO_REFUND_COMMAND，不会删除或重建已有表。
