-- V2.1 退款业务生命周期升级：执行前请完成数据库备份。
-- 本脚本仅扩展既有表，不删除、重命名或重建任何业务表。
USE AI_AGENT_STATION;

ALTER TABLE DEMO_AFTER_SALES_CASE
    ADD COLUMN OPERATOR_ID VARCHAR(128) NOT NULL DEFAULT '',
    ADD COLUMN DECISION_ID VARCHAR(128) NOT NULL DEFAULT '',
    ADD COLUMN DECISION_NOTE VARCHAR(500) NOT NULL DEFAULT '',
    ADD COLUMN REVIEWED_AT DATETIME(6) DEFAULT NULL,
    ADD COLUMN FAILURE_CODE VARCHAR(64) NOT NULL DEFAULT '';

ALTER TABLE DEMO_REFUND_COMMAND
    ADD COLUMN RETRY_ID VARCHAR(128) NOT NULL DEFAULT '',
    ADD COLUMN ATTEMPT_COUNT INT NOT NULL DEFAULT 0,
    ADD COLUMN NEXT_ATTEMPT_AT DATETIME(6) DEFAULT NULL,
    ADD COLUMN LEASE_UNTIL DATETIME(6) DEFAULT NULL,
    ADD COLUMN FAILURE_CODE VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN UPDATED_AT DATETIME(6) DEFAULT NULL;

UPDATE DEMO_REFUND_COMMAND
SET STATUS = CASE WHEN STATUS = 'ACCEPTED' THEN 'COMPLETED' ELSE STATUS END,
    NEXT_ATTEMPT_AT = COALESCE(NEXT_ATTEMPT_AT, CREATED_AT),
    UPDATED_AT = COALESCE(UPDATED_AT, CREATED_AT);

UPDATE DEMO_AFTER_SALES_CASE CASES
JOIN DEMO_REFUND_COMMAND COMMANDS ON COMMANDS.CASE_ID = CASES.CASE_ID
SET CASES.REFUND_ID = COMMANDS.REFUND_ID,
    CASES.STATUS = CASE
        WHEN COMMANDS.STATUS = 'COMPLETED' AND CASES.STATUS = 'REFUND_PROCESSING' THEN 'COMPLETED'
        ELSE CASES.STATUS
    END,
    CASES.UPDATED_AT = CURRENT_TIMESTAMP(6)
WHERE CASES.REFUND_ID = '' OR CASES.STATUS = 'REFUND_PROCESSING';

ALTER TABLE DEMO_REFUND_COMMAND
    MODIFY NEXT_ATTEMPT_AT DATETIME(6) NOT NULL,
    MODIFY UPDATED_AT DATETIME(6) NOT NULL,
    ADD CONSTRAINT UK_DEMO_REFUND_COMMAND_CASE UNIQUE (CASE_ID),
    ADD INDEX IDX_DEMO_REFUND_COMMAND_DUE (STATUS, NEXT_ATTEMPT_AT, LEASE_UNTIL);
