-- 订单/物流/售后申请 V2 升级脚本。仅在完成备份后的非生产 MySQL 执行。
-- 不删除旧数据；执行后再运行 ai-agent-station.sql 以写入演示订单、商品和轨迹。
USE AI_AGENT_STATION;

CREATE TABLE IF NOT EXISTS DEMO_ORDER_ITEM (
    ITEM_ID VARCHAR(64) NOT NULL,
    ORDER_ID VARCHAR(64) NOT NULL,
    PRODUCT_NAME VARCHAR(256) NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(19, 2) NOT NULL,
    CONSTRAINT PK_DEMO_ORDER_ITEM PRIMARY KEY (ITEM_ID),
    INDEX IDX_DEMO_ORDER_ITEM_ORDER (ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS DEMO_LOGISTICS_EVENT (
    EVENT_ID VARCHAR(64) NOT NULL,
    ORDER_ID VARCHAR(64) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    LOCATION VARCHAR(256) DEFAULT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    OCCURRED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_DEMO_LOGISTICS_EVENT PRIMARY KEY (EVENT_ID),
    INDEX IDX_DEMO_LOGISTICS_EVENT_ORDER_TIME (ORDER_ID, OCCURRED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS DEMO_AFTER_SALES_CASE (
    CASE_ID VARCHAR(64) NOT NULL,
    WORKFLOW_RUN_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(64) NOT NULL,
    ORDER_ID VARCHAR(64) NOT NULL,
    REQUEST_TYPE VARCHAR(32) NOT NULL,
    REFUND_REASON VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL DEFAULT '',
    HANDLING_MODE VARCHAR(32) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    AMOUNT DECIMAL(19, 2) DEFAULT NULL,
    CURRENCY VARCHAR(8) NOT NULL DEFAULT '',
    REFUND_ID VARCHAR(64) NOT NULL DEFAULT '',
    VERSION BIGINT NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_DEMO_AFTER_SALES_CASE PRIMARY KEY (CASE_ID),
    CONSTRAINT UK_DEMO_AFTER_SALES_CASE_RUN UNIQUE (WORKFLOW_RUN_ID),
    CONSTRAINT UK_DEMO_AFTER_SALES_CASE_ORDER UNIQUE (USER_ID, ORDER_ID, REQUEST_TYPE),
    INDEX IDX_DEMO_AFTER_SALES_CASE_ORDER (ORDER_ID, USER_ID, UPDATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET @ADD_CASE_ID = (
    SELECT CASE WHEN EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'AI_AGENT_STATION'
          AND TABLE_NAME = 'DEMO_REFUND_COMMAND'
          AND COLUMN_NAME = 'CASE_ID'
    ) THEN 'SELECT 1'
    ELSE 'ALTER TABLE DEMO_REFUND_COMMAND ADD COLUMN CASE_ID VARCHAR(64) DEFAULT NULL AFTER WORKFLOW_RUN_ID'
    END
);
PREPARE ADD_CASE_ID FROM @ADD_CASE_ID;
EXECUTE ADD_CASE_ID;
DEALLOCATE PREPARE ADD_CASE_ID;

-- 历史退款命令没有独立申请单，以原 WorkflowRunId 作为可审计的关联值。
UPDATE DEMO_REFUND_COMMAND
SET CASE_ID = WORKFLOW_RUN_ID
WHERE CASE_ID IS NULL OR CASE_ID = '';

ALTER TABLE DEMO_REFUND_COMMAND MODIFY COLUMN CASE_ID VARCHAR(64) NOT NULL;
