-- 旧退款售后表人工清理脚本。
-- 本文件不会被应用自动执行。执行前必须完成备份，并确认不再需要旧售后数据。
USE AI_AGENT_STATION;

DROP TABLE IF EXISTS AFTER_SALES_OUTBOX;
DROP TABLE IF EXISTS AGENT_TURN;
DROP TABLE IF EXISTS CHECKPOINT;
DROP TABLE IF EXISTS REFUND_COMMAND;
DROP TABLE IF EXISTS AFTER_SALES_CASE;
