-- QuestionCard 与会话记忆升级脚本。执行前请在维护窗口备份 WORKFLOW_RUN。
USE AI_AGENT_STATION;

ALTER TABLE WORKFLOW_RUN ADD COLUMN QUESTION_JSON LONGTEXT DEFAULT NULL AFTER STATE_JSON;

-- 旧版退款确认运行统一迁移为新的通用等待用户输入状态。
UPDATE WORKFLOW_RUN
SET STATUS = 'WAITING_USER_INPUT'
WHERE STATUS IN ('WAITING_CONFIRMATION', 'NEEDS_INPUT', 'NEEDS_CONFIRMATION');

CREATE TABLE AGENT_MEMORY_SOURCE (
    SOURCE_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    SESSION_ID VARCHAR(128) NOT NULL,
    REQUEST_ID VARCHAR(128) NOT NULL,
    SOURCE_TYPE VARCHAR(32) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_AGENT_MEMORY_SOURCE PRIMARY KEY (SOURCE_ID),
    INDEX IDX_AGENT_MEMORY_SOURCE_SESSION (USER_ID, SESSION_ID, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE AGENT_MEMORY_ENTRY (
    ENTRY_ID VARCHAR(64) NOT NULL,
    SOURCE_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    SESSION_ID VARCHAR(128) NOT NULL,
    CONTENT VARCHAR(4000) NOT NULL,
    DELETED TINYINT(1) NOT NULL DEFAULT 0,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_AGENT_MEMORY_ENTRY PRIMARY KEY (ENTRY_ID),
    CONSTRAINT FK_AGENT_MEMORY_ENTRY_SOURCE FOREIGN KEY (SOURCE_ID) REFERENCES AGENT_MEMORY_SOURCE (SOURCE_ID),
    INDEX IDX_AGENT_MEMORY_ENTRY_OWNER (USER_ID, SESSION_ID, UPDATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE AGENT_MEMORY_EVIDENCE (
    EVIDENCE_ID VARCHAR(64) NOT NULL,
    ENTRY_ID VARCHAR(64) NOT NULL,
    EVIDENCE_TYPE VARCHAR(32) NOT NULL,
    EVIDENCE_REF VARCHAR(512) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT PK_AGENT_MEMORY_EVIDENCE PRIMARY KEY (EVIDENCE_ID),
    CONSTRAINT FK_AGENT_MEMORY_EVIDENCE_ENTRY FOREIGN KEY (ENTRY_ID) REFERENCES AGENT_MEMORY_ENTRY (ENTRY_ID),
    INDEX IDX_AGENT_MEMORY_EVIDENCE_ENTRY (ENTRY_ID, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
