-- Commerce Guardian Agent P5 只读盘点。
-- 在目标库备份副本或只读账号下执行；本文件不包含 INSERT、UPDATE、DELETE、DDL 或锁表语句。

SELECT 'WORKFLOW_RUNS' AS REPORT,
       ORCHESTRATION_VERSION,
       STATUS,
       COUNT(*) AS RECORD_COUNT
FROM AGENT_WORKFLOW_RUN
GROUP BY ORCHESTRATION_VERSION, STATUS
ORDER BY ORCHESTRATION_VERSION, STATUS;

SELECT 'LEGACY_NON_TERMINAL_RUNS' AS REPORT,
       COUNT(*) AS RECORD_COUNT
FROM AGENT_WORKFLOW_RUN
WHERE ORCHESTRATION_VERSION IN ('LEGACY_V1', 'EXPEDITE_GRAPH_V1', 'EXPEDITE_GRAPH_V2')
  AND STATUS NOT IN ('COMPLETED', 'REJECTED', 'FAILED');

SELECT 'OPEN_INTERACTIONS' AS REPORT,
       'QUESTION_CARD' AS INTERACTION_TYPE,
       COUNT(*) AS RECORD_COUNT
FROM AGENT_QUESTION_CARD
WHERE STATUS = 'OPEN'
UNION ALL
SELECT 'OPEN_INTERACTIONS',
       'WORKFLOW_CHECKPOINT',
       COUNT(*)
FROM AGENT_WORKFLOW_CHECKPOINT
WHERE STATUS IN ('OPEN', 'APPROVED');

SELECT 'UNSETTLED_COMMANDS' AS REPORT,
       STATUS,
       OUTCOME_STATUS,
       COUNT(*) AS RECORD_COUNT
FROM EXTERNAL_ACTION_COMMAND
WHERE STATUS IN ('PENDING', 'PROCESSING', 'RETRY_WAIT', 'VERIFY_WAIT',
                 'MANUAL_RETRY_REQUIRED', 'MANUAL_VERIFICATION_REQUIRED')
GROUP BY STATUS, OUTCOME_STATUS
ORDER BY STATUS, OUTCOME_STATUS;

SELECT 'PENDING_CONTINUATIONS' AS REPORT,
       COUNT(*) AS RECORD_COUNT
FROM AGENT_TURN
WHERE CONTINUATION_JSON IS NOT NULL
  AND STATUS NOT IN ('COMPLETED', 'FAILED', 'CANCELLED', 'TIMED_OUT');

SELECT 'GRAPH_SNAPSHOTS_BY_VERSION' AS REPORT,
       ORCHESTRATION_VERSION,
       COUNT(*) AS RECORD_COUNT
FROM AGENT_GRAPH_SNAPSHOT
GROUP BY ORCHESTRATION_VERSION
ORDER BY ORCHESTRATION_VERSION;
