server:
  port: 8090

thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

spring:
  datasource:
    mysql:
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/ai-agent-station?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 15
        idle-timeout: 30000
        maximum-pool-size: 25
        max-lifetime: 1800000
        connection-timeout: 30000
    pgvector:
      username: postgres
      password: postgres
      url: jdbc:postgresql://106.52.3.218:5432/ai-agent-station
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5
        minimum-idle: 2
        idle-timeout: 30000
        connection-timeout: 30000
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      api-key: sk-0ec8457a16644d5ca60a3468b20463e2
      embedding:
        options:
          model: text-embedding-v4
    agent:
      auto-config:
        enabled: false
        client-ids: 2101,2102,2103
#        client-ids: 3101,3102,3103,3104,4101,4102,4103,4104,5101,5102,5103,5104

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
