spring:
  config:
    name: ai-agent-station-app
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  profiles:
    active: dev

server:
  port: 8090

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
